services:
  - type: web
    name: backend
    env: node
    plan: free
    buildCommand: npm install && npx nx build backend
    startCommand: node dist/apps/backend/main.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 300
